name: mobx_cli
description: A Delicious Command Line Interface for Mobx.
version: 0.1.0-dev.1
homepage: https://github.com/amondnet/mobx_cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  io: ^1.0.0
  mason: ^0.0.1-dev.31
  meta: ^1.4.0
  path: ^1.8.0
  usage: ^4.0.2

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.4
  build_verify: ^2.0.0
  build_version: ^2.0.3
  mockito: ^5.0.9
  test: ^1.17.5

executables:
  groovin: